name:                clips
version:             0.1.0.0
github:              Skyb0rg007/clips
license:             MIT
author:              Skye Soss
maintainer:          Skye Soss <skyler.soss@gmail.com>
copyright:           2019 Skye Soss

extra-source-files:
- README.md

synopsis:            Haskell bindings to CLIPS
# category:            Web

description:         Please see the README on GitHub at <https://github.com/Skyb0rg007/clips#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall

flags:
  system-clips:
    default: false
    manual: true
    description: "Use CLIPS found on the system - must be version 6.4"
  clips-debug:
    default: false
    manual: true
    description: "Compile CLIPS with debug symbols"

library:
  source-dirs:  src
  build-tools:  c2hs
  dependencies: clips-clib
  # We need to manually list these so c2hs runs in the right order
  exposed-modules:
  - Clips.Raw.Types
  - Clips.Raw.Core
  - Clips.Raw.Advanced

internal-libraries:
  clips-clib:
    when:
      - condition: flag(system-clips)
        then:
          extra-libraries: clips
        else:
          include-dirs: cbits/include
          extra-libraries: m
          cc-options: -std=c99

          when:
            - condition: os(darwin)
              cc-options:
              - -DDARWIN
              - -Wall
              - -Wundef
              - -Wpointer-arith
              - -Wshadow
              - -Wstrict-aliasing 
              - -Winline
              - -Wredundant-decls
              - -Waggregate-return

            - condition: os(linux)
              cc-options:
              - -DLINUX
              - -Wall
              - -Wundef
              - -Wpointer-arith
              - -Wshadow
              - -Wstrict-aliasing
              - -Winline
              - -Wmissing-declarations
              - -Wredundant-decls
              - -Wmissing-prototypes
              - -Wnested-externs
              - -Wstrict-prototypes
              - -Waggregate-return
              - -Wno-implicit

            - condition: os(windows)
              cc-options:
              - -DWIN_GCC

            - condition: flag(clips-debug)
              then:
                cc-options: -O0 -g
              else:
                cc-options: -O3 -fno-strict-aliasing

          c-sources:
          - cbits/src/agenda.c
          - cbits/src/analysis.c
          - cbits/src/argacces.c
          - cbits/src/bload.c
          - cbits/src/bmathfun.c
          - cbits/src/bsave.c
          - cbits/src/classcom.c
          - cbits/src/classexm.c
          - cbits/src/classfun.c
          - cbits/src/classinf.c
          - cbits/src/classini.c
          - cbits/src/classpsr.c
          - cbits/src/clsltpsr.c
          - cbits/src/commline.c
          - cbits/src/conscomp.c
          - cbits/src/constrct.c
          - cbits/src/constrnt.c
          - cbits/src/crstrtgy.c
          - cbits/src/cstrcbin.c
          - cbits/src/cstrccom.c
          - cbits/src/cstrcpsr.c
          - cbits/src/cstrnbin.c
          - cbits/src/cstrnchk.c
          - cbits/src/cstrncmp.c
          - cbits/src/cstrnops.c
          - cbits/src/cstrnpsr.c
          - cbits/src/cstrnutl.c
          - cbits/src/default.c
          - cbits/src/defins.c
          - cbits/src/developr.c
          - cbits/src/dffctbin.c
          - cbits/src/dffctbsc.c
          - cbits/src/dffctcmp.c
          - cbits/src/dffctdef.c
          - cbits/src/dffctpsr.c
          - cbits/src/dffnxbin.c
          - cbits/src/dffnxcmp.c
          - cbits/src/dffnxexe.c
          - cbits/src/dffnxfun.c
          - cbits/src/dffnxpsr.c
          - cbits/src/dfinsbin.c
          - cbits/src/dfinscmp.c
          - cbits/src/drive.c
          - cbits/src/emathfun.c
          - cbits/src/engine.c
          - cbits/src/envrnbld.c
          - cbits/src/envrnmnt.c
          - cbits/src/evaluatn.c
          - cbits/src/expressn.c
          - cbits/src/exprnbin.c
          - cbits/src/exprnops.c
          - cbits/src/exprnpsr.c
          - cbits/src/extnfunc.c
          - cbits/src/factbin.c
          - cbits/src/factbld.c
          - cbits/src/factcmp.c
          - cbits/src/factcom.c
          - cbits/src/factfun.c
          - cbits/src/factgen.c
          - cbits/src/facthsh.c
          - cbits/src/factlhs.c
          - cbits/src/factmch.c
          - cbits/src/factmngr.c
          - cbits/src/factprt.c
          - cbits/src/factqpsr.c
          - cbits/src/factqury.c
          - cbits/src/factrete.c
          - cbits/src/factrhs.c
          - cbits/src/filecom.c
          - cbits/src/filertr.c
          - cbits/src/fileutil.c
          - cbits/src/generate.c
          - cbits/src/genrcbin.c
          - cbits/src/genrccmp.c
          - cbits/src/genrccom.c
          - cbits/src/genrcexe.c
          - cbits/src/genrcfun.c
          - cbits/src/genrcpsr.c
          - cbits/src/globlbin.c
          - cbits/src/globlbsc.c
          - cbits/src/globlcmp.c
          - cbits/src/globlcom.c
          - cbits/src/globldef.c
          - cbits/src/globlpsr.c
          - cbits/src/immthpsr.c
          - cbits/src/incrrset.c
          - cbits/src/inherpsr.c
          - cbits/src/inscom.c
          - cbits/src/insfile.c
          - cbits/src/insfun.c
          - cbits/src/insmngr.c
          - cbits/src/insmoddp.c
          - cbits/src/insmult.c
          - cbits/src/inspsr.c
          - cbits/src/insquery.c
          - cbits/src/insqypsr.c
          - cbits/src/iofun.c
          - cbits/src/lgcldpnd.c
          # -bits/srcrc/main.c
          - cbits/src/memalloc.c
          - cbits/src/miscfun.c
          - cbits/src/modulbin.c
          - cbits/src/modulbsc.c
          - cbits/src/modulcmp.c
          - cbits/src/moduldef.c
          - cbits/src/modulpsr.c
          - cbits/src/modulutl.c
          - cbits/src/msgcom.c
          - cbits/src/msgfun.c
          - cbits/src/msgpass.c
          - cbits/src/msgpsr.c
          - cbits/src/multifld.c
          - cbits/src/multifun.c
          - cbits/src/objbin.c
          - cbits/src/objcmp.c
          - cbits/src/objrtbin.c
          - cbits/src/objrtbld.c
          - cbits/src/objrtcmp.c
          - cbits/src/objrtfnx.c
          - cbits/src/objrtgen.c
          - cbits/src/objrtmch.c
          - cbits/src/parsefun.c
          - cbits/src/pattern.c
          - cbits/src/pprint.c
          - cbits/src/prccode.c
          - cbits/src/prcdrfun.c
          - cbits/src/prcdrpsr.c
          - cbits/src/prdctfun.c
          - cbits/src/prntutil.c
          - cbits/src/proflfun.c
          - cbits/src/reorder.c
          - cbits/src/reteutil.c
          - cbits/src/retract.c
          - cbits/src/router.c
          - cbits/src/rulebin.c
          - cbits/src/rulebld.c
          - cbits/src/rulebsc.c
          - cbits/src/rulecmp.c
          - cbits/src/rulecom.c
          - cbits/src/rulecstr.c
          - cbits/src/ruledef.c
          - cbits/src/ruledlt.c
          - cbits/src/rulelhs.c
          - cbits/src/rulepsr.c
          - cbits/src/scanner.c
          - cbits/src/sortfun.c
          - cbits/src/strngfun.c
          - cbits/src/strngrtr.c
          - cbits/src/symblbin.c
          - cbits/src/symblcmp.c
          - cbits/src/symbol.c
          - cbits/src/sysdep.c
          - cbits/src/textpro.c
          - cbits/src/tmpltbin.c
          - cbits/src/tmpltbsc.c
          - cbits/src/tmpltcmp.c
          - cbits/src/tmpltdef.c
          - cbits/src/tmpltfun.c
          - cbits/src/tmpltlhs.c
          - cbits/src/tmpltpsr.c
          - cbits/src/tmpltrhs.c
          - cbits/src/tmpltutl.c
          - cbits/src/userdata.c
          - cbits/src/userfunctions.c
          - cbits/src/utility.c
          - cbits/src/watch.c

tests:
  clips-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools: hspec-discover
    dependencies:
    - hspec
    - clips
    - clips-clib
